[registry]
endpoint = "https://schemas.holaplex.tools/"

[schemas]
organization = 5
nfts = 26
customer = 2
treasury = 16
credits = 6
credits_mpsc = 2
credential = 2
webhook = 2
solana_nfts = 7
polygon_nfts = 3
